version: '3.4'

services:
 
  backend:
    image: "moviereviews-backend"
    build:
      
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000

    container_name: backend
 
      
     

    depends_on:
      - db
    
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
   

networks:
  mern-stack-net:
   driver: bridge
  
volumes:
    mongo-data:
      driver: local
  


  
